# Generated by Django 5.0.4 on 2024-04-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PttStockDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255)),
                ('paragraph_link', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ptt_stock_dict',
            },
        ),
        migrations.CreateModel(
            name='PttStockParagraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_link', models.CharField(max_length=255)),
                ('paragraph_author', models.CharField(max_length=255)),
                ('paragraph_title', models.CharField(max_length=255)),
                ('paragraph_published_time', models.DateTimeField()),
                ('paragraph_content', models.TextField()),
                ('paragraph_ip', models.CharField(max_length=32)),
                ('paragraph_country', models.CharField(max_length=32)),
                ('comments', models.JSONField()),
                ('status', models.CharField(max_length=8)),
                ('md5_hash', models.CharField(max_length=255)),
                ('paragraph_content_token_count', models.IntegerField()),
                ('comments_token_count', models.IntegerField()),
                ('paragraph_tag', models.CharField(max_length=32)),
                ('paragraph_stock_targets', models.JSONField()),
            ],
            options={
                'db_table': 'ptt_stock_paragraphs',
            },
        ),
        migrations.CreateModel(
            name='PttStockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'ptt_stock_setting',
            },
        ),
        migrations.CreateModel(
            name='PttStockTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'ptt_stock_targets',
            },
        ),
    ]
