# Generated by Django 5.0.4 on 2024-04-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_stock_vane_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pttstockparagraphs',
            name='page_url',
            field=models.CharField(default='https://www.ptt.cc/bbs/Stock/index.html', max_length=255),
        ),
    ]
