# Generated by Django 5.0.4 on 2024-05-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_stock_vane_api', '0002_pttstockparagraphs_page_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PttStockDict',
        ),
    ]
