# Generated by Django 5.0.7 on 2024-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_stock_vane_api', '0003_delete_pttstockdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='pttstockparagraphs',
            name='done_analyze',
            field=models.BooleanField(default=False),
        ),
    ]
